export default function () {
  return {
    "code": 200,
    "data": [{
      "cId": "7",
      "cRootId": "7",
      "cParentId": "7",
      "cNameShort": "系统",
      "cNameLong": "系统管理",
      "cAction": "/ajax/sys/",
      "cWidgetTypeId": 1,
      "cOrderNum": 7,
      "cIcon": ""
    }, {
      "cId": "7-1",
      "cRootId": "7",
      "cParentId": "7",
      "cNameShort": "",
      "cNameLong": "组织管理",
      "cAction": "/ajax/sys/",
      "cWidgetTypeId": 2,
      "cOrderNum": 1,
      "cIcon": ""
    }, {
      "cId": "7-1-1",
      "cRootId": "7",
      "cParentId": "7-1",
      "cNameShort": "",
      "cNameLong": "新建",
      "cAction": "/ajax/sys/org/add.do",
      "cWidgetTypeId": 3,
      "cOrderNum": 1,
      "cIcon": "",
      "cCommandTypeId": "1"
    }, {
      "cId": "7-1-2",
      "cRootId": "7",
      "cParentId": "7-1",
      "cNameShort": "",
      "cNameLong": "编辑",
      "cAction": "/ajax/sys/org/mod.do",
      "cWidgetTypeId": 3,
      "cOrderNum": 2,
      "cIcon": "",
      "cCommandTypeId": "2"
    }, {
      "cId": "7-1-3",
      "cRootId": "7",
      "cParentId": "7-1",
      "cNameShort": "",
      "cNameLong": "删除",
      "cAction": "/ajax/sys/org/del.do",
      "cWidgetTypeId": 3,
      "cOrderNum": 3,
      "cIcon": "",
      "cCommandTypeId": "3"
    }, {
      "cId": "7-2",
      "cRootId": "7",
      "cParentId": "7",
      "cNameShort": "",
      "cNameLong": "角色管理",
      "cAction": "/ajax/sys/role/",
      "cWidgetTypeId": 2,
      "cOrderNum": 2,
      "cIcon": ""
    }, {
      "cId": "7-2-1",
      "cRootId": "7",
      "cParentId": "7-2",
      "cNameShort": "",
      "cNameLong": "新建",
      "cAction": "/ajax/sys/role/add.do",
      "cWidgetTypeId": 3,
      "cOrderNum": 1,
      "cIcon": "",
      "cCommandTypeId": "1"
    }, {
      "cId": "7-2-2",
      "cRootId": "7",
      "cParentId": "7-2",
      "cNameShort": "",
      "cNameLong": "编辑",
      "cAction": "/ajax/sys/role/mod.do",
      "cWidgetTypeId": 3,
      "cOrderNum": 2,
      "cIcon": "",
      "cCommandTypeId": "2"
    }, {
      "cId": "7-2-3",
      "cRootId": "7",
      "cParentId": "7-2",
      "cNameShort": "",
      "cNameLong": "删除",
      "cAction": "/ajax/sys/role/del.do",
      "cWidgetTypeId": 3,
      "cOrderNum": 3,
      "cIcon": "",
      "cCommandTypeId": "3"
    }, {
      "cId": "7-3",
      "cRootId": "7",
      "cParentId": "7",
      "cNameShort": "",
      "cNameLong": "权限管理",
      "cAction": "/ajax/sys/role/",
      "cWidgetTypeId": 2,
      "cOrderNum": 3,
      "cIcon": ""
    }, {
      "cId": "7-3-1",
      "cRootId": "7",
      "cParentId": "7-3",
      "cNameShort": "",
      "cNameLong": "授权",
      "cAction": "/ajax/sys/role/auth.do",
      "cWidgetTypeId": 3,
      "cOrderNum": 1,
      "cIcon": "",
      "cCommandTypeId": "4"
    }, {
      "cId": "7-4",
      "cRootId": "7",
      "cParentId": "7",
      "cNameShort": "",
      "cNameLong": "用户管理",
      "cAction": "/ajax/sys/user/",
      "cWidgetTypeId": 2,
      "cOrderNum": 4,
      "cIcon": ""
    }, {
      "cId": "7-4-1",
      "cRootId": "7",
      "cParentId": "7-4",
      "cNameShort": "",
      "cNameLong": "新建",
      "cAction": "/ajax/sys/user/add.do",
      "cWidgetTypeId": 3,
      "cOrderNum": 1,
      "cIcon": "",
      "cCommandTypeId": "1"
    }, {
      "cId": "7-4-2",
      "cRootId": "7",
      "cParentId": "7-4",
      "cNameShort": "",
      "cNameLong": "编辑",
      "cAction": "/ajax/sys/user/mod.do",
      "cWidgetTypeId": 3,
      "cOrderNum": 2,
      "cIcon": "",
      "cCommandTypeId": "2"
    }, {
      "cId": "7-4-3",
      "cRootId": "7",
      "cParentId": "7-4",
      "cNameShort": "",
      "cNameLong": "删除",
      "cAction": "/ajax/sys/user/del.do",
      "cWidgetTypeId": 3,
      "cOrderNum": 3,
      "cIcon": "",
      "cCommandTypeId": "3"
    }, {
      "cId": "7-4-4",
      "cRootId": "7",
      "cParentId": "7-4",
      "cNameShort": "",
      "cNameLong": "启用/停用",
      "cAction": "/ajax/sys/user/enable.do",
      "cWidgetTypeId": 3,
      "cOrderNum": 4,
      "cIcon": "",
      "cCommandTypeId": "5"
    }],
    "detail": "Ok"
  }
}