export default function getProfile() {
  return {
    code: 200,
    data: {
      cId: "16010100000001",
      cLoginname: "sp-admin",
      cLoginpass: "14e1b600b1fd579f47433b88e8d85291",
      cRealname: "校客管理员",
      cNickname: "校客管理员",
      cPhone: "13600000000",
      cEmail: "sp-admin@schoolpal.com",
      cQq: "6666666",
      cAvailable: true,
      cOrgId: "16010100000001",
      cOrgRootId: "16010100000001",
      cCreator: "16010100000001",
      cCreateTime: "Dec 27, 2016 2:03:38 PM",
      cLastVisitTime: "Dec 4, 2017 3:21:08 AM",
      cLastVisitIp: "15.211.153.74",
      org: {
        cId: "16010100000001",
        cCode: "sp",
        cName: "校客科技",
        cAddress: "上地软件园1号",
        cState: "北京市",
        cCity: "海淀区",
        cCounty: "",
        cStateCode: "110000",
        cCityCode: "110108",
        cCountyCode: "",
        cOwner: "曹磊",
        cOwnerPhone: "13666666666",
        cParentId: "16010100000001",
        cRootId: "16010100000001",
        level: 0,
        parent: false
      },
      roles: [
        {
          cId: "16010100000001",
          cOrgId: "16010100000001",
          cName: "系统管理员",
          cDesc: "系统超级管理员",
          cRankId: 4,
          functions: [
            {
              cId: "7",
              cRootId: "7",
              cParentId: "7",
              cNameShort: "系统",
              cNameLong: "系统管理",
              cAction: "/ajax/sys/",
              cWidgetTypeId: 1,
              cOrderNum: 7,
              cIcon: "",
              WidgetType: "Menu"
            },
            {
              cId: "7-1",
              cRootId: "7",
              cParentId: "7",
              cNameShort: "",
              cNameLong: "组织管理",
              cAction: "/ajax/sys/",
              cWidgetTypeId: 2,
              cOrderNum: 1,
              cIcon: "",
              WidgetType: "MenuItem"
            },
            {
              cId: "7-1-1",
              cRootId: "7",
              cParentId: "7-1",
              cNameShort: "",
              cNameLong: "新建",
              cAction: "/ajax/sys/org/add.do",
              cWidgetTypeId: 3,
              cOrderNum: 1,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Add",
              CommandName: "Add"
            },
            {
              cId: "7-1-2",
              cRootId: "7",
              cParentId: "7-1",
              cNameShort: "",
              cNameLong: "编辑",
              cAction: "/ajax/sys/org/mod.do",
              cWidgetTypeId: 3,
              cOrderNum: 2,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Mod",
              CommandName: "Modify"
            },
            {
              cId: "7-1-3",
              cRootId: "7",
              cParentId: "7-1",
              cNameShort: "",
              cNameLong: "删除",
              cAction: "/ajax/sys/org/del.do",
              cWidgetTypeId: 3,
              cOrderNum: 3,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Del",
              CommandName: "Delete"
            },
            {
              cId: "7-2",
              cRootId: "7",
              cParentId: "7",
              cNameShort: "",
              cNameLong: "角色管理",
              cAction: "/ajax/sys/role/",
              cWidgetTypeId: 2,
              cOrderNum: 2,
              cIcon: "",
              WidgetType: "MenuItem"
            },
            {
              cId: "7-2-1",
              cRootId: "7",
              cParentId: "7-2",
              cNameShort: "",
              cNameLong: "新建",
              cAction: "/ajax/sys/role/add.do",
              cWidgetTypeId: 3,
              cOrderNum: 1,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Add",
              CommandName: "Add"
            },
            {
              cId: "7-2-2",
              cRootId: "7",
              cParentId: "7-2",
              cNameShort: "",
              cNameLong: "编辑",
              cAction: "/ajax/sys/role/mod.do",
              cWidgetTypeId: 3,
              cOrderNum: 2,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Mod",
              CommandName: "Modify"
            },
            {
              cId: "7-2-3",
              cRootId: "7",
              cParentId: "7-2",
              cNameShort: "",
              cNameLong: "删除",
              cAction: "/ajax/sys/role/del.do",
              cWidgetTypeId: 3,
              cOrderNum: 3,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Del",
              CommandName: "Delete"
            },
            {
              cId: "7-3",
              cRootId: "7",
              cParentId: "7",
              cNameShort: "",
              cNameLong: "权限管理",
              cAction: "/ajax/sys/role/",
              cWidgetTypeId: 2,
              cOrderNum: 3,
              cIcon: "",
              WidgetType: "MenuItem"
            },
            {
              cId: "7-3-1",
              cRootId: "7",
              cParentId: "7-3",
              cNameShort: "",
              cNameLong: "授权",
              cAction: "/ajax/sys/role/auth.do",
              cWidgetTypeId: 3,
              cOrderNum: 1,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Auth",
              CommandName: "Authorize"
            },
            {
              cId: "7-4",
              cRootId: "7",
              cParentId: "7",
              cNameShort: "",
              cNameLong: "用户管理",
              cAction: "/ajax/sys/user/",
              cWidgetTypeId: 2,
              cOrderNum: 4,
              cIcon: "",
              WidgetType: "MenuItem"
            },
            {
              cId: "7-4-1",
              cRootId: "7",
              cParentId: "7-4",
              cNameShort: "",
              cNameLong: "新建",
              cAction: "/ajax/sys/user/add.do",
              cWidgetTypeId: 3,
              cOrderNum: 1,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Add",
              CommandName: "Add"
            },
            {
              cId: "7-4-2",
              cRootId: "7",
              cParentId: "7-4",
              cNameShort: "",
              cNameLong: "编辑",
              cAction: "/ajax/sys/user/mod.do",
              cWidgetTypeId: 3,
              cOrderNum: 2,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Mod",
              CommandName: "Modify"
            },
            {
              cId: "7-4-3",
              cRootId: "7",
              cParentId: "7-4",
              cNameShort: "",
              cNameLong: "删除",
              cAction: "/ajax/sys/user/del.do",
              cWidgetTypeId: 3,
              cOrderNum: 3,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Del",
              CommandName: "Delete"
            },
            {
              cId: "7-4-4",
              cRootId: "7",
              cParentId: "7-4",
              cNameShort: "",
              cNameLong: "启用/停用",
              cAction: "/ajax/sys/user/enable.do",
              cWidgetTypeId: 3,
              cOrderNum: 4,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Enable",
              CommandName: "Enable"
            }
          ]
        }
      ],
      roleIndex: {
        "16010100000001": {
          cId: "16010100000001",
          cOrgId: "16010100000001",
          cName: "系统管理员",
          cDesc: "系统超级管理员",
          cRankId: 4,
          functions: [
            {
              cId: "7",
              cRootId: "7",
              cParentId: "7",
              cNameShort: "系统",
              cNameLong: "系统管理",
              cAction: "/ajax/sys/",
              cWidgetTypeId: 1,
              cOrderNum: 7,
              cIcon: "",
              WidgetType: "Menu"
            },
            {
              cId: "7-1",
              cRootId: "7",
              cParentId: "7",
              cNameShort: "",
              cNameLong: "组织管理",
              cAction: "/ajax/sys/",
              cWidgetTypeId: 2,
              cOrderNum: 1,
              cIcon: "",
              WidgetType: "MenuItem"
            },
            {
              cId: "7-1-1",
              cRootId: "7",
              cParentId: "7-1",
              cNameShort: "",
              cNameLong: "新建",
              cAction: "/ajax/sys/org/add.do",
              cWidgetTypeId: 3,
              cOrderNum: 1,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Add",
              CommandName: "Add"
            },
            {
              cId: "7-1-2",
              cRootId: "7",
              cParentId: "7-1",
              cNameShort: "",
              cNameLong: "编辑",
              cAction: "/ajax/sys/org/mod.do",
              cWidgetTypeId: 3,
              cOrderNum: 2,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Mod",
              CommandName: "Modify"
            },
            {
              cId: "7-1-3",
              cRootId: "7",
              cParentId: "7-1",
              cNameShort: "",
              cNameLong: "删除",
              cAction: "/ajax/sys/org/del.do",
              cWidgetTypeId: 3,
              cOrderNum: 3,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Del",
              CommandName: "Delete"
            },
            {
              cId: "7-2",
              cRootId: "7",
              cParentId: "7",
              cNameShort: "",
              cNameLong: "角色管理",
              cAction: "/ajax/sys/role/",
              cWidgetTypeId: 2,
              cOrderNum: 2,
              cIcon: "",
              WidgetType: "MenuItem"
            },
            {
              cId: "7-2-1",
              cRootId: "7",
              cParentId: "7-2",
              cNameShort: "",
              cNameLong: "新建",
              cAction: "/ajax/sys/role/add.do",
              cWidgetTypeId: 3,
              cOrderNum: 1,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Add",
              CommandName: "Add"
            },
            {
              cId: "7-2-2",
              cRootId: "7",
              cParentId: "7-2",
              cNameShort: "",
              cNameLong: "编辑",
              cAction: "/ajax/sys/role/mod.do",
              cWidgetTypeId: 3,
              cOrderNum: 2,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Mod",
              CommandName: "Modify"
            },
            {
              cId: "7-2-3",
              cRootId: "7",
              cParentId: "7-2",
              cNameShort: "",
              cNameLong: "删除",
              cAction: "/ajax/sys/role/del.do",
              cWidgetTypeId: 3,
              cOrderNum: 3,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Del",
              CommandName: "Delete"
            },
            {
              cId: "7-3",
              cRootId: "7",
              cParentId: "7",
              cNameShort: "",
              cNameLong: "权限管理",
              cAction: "/ajax/sys/role/",
              cWidgetTypeId: 2,
              cOrderNum: 3,
              cIcon: "",
              WidgetType: "MenuItem"
            },
            {
              cId: "7-3-1",
              cRootId: "7",
              cParentId: "7-3",
              cNameShort: "",
              cNameLong: "授权",
              cAction: "/ajax/sys/role/auth.do",
              cWidgetTypeId: 3,
              cOrderNum: 1,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Auth",
              CommandName: "Authorize"
            },
            {
              cId: "7-4",
              cRootId: "7",
              cParentId: "7",
              cNameShort: "",
              cNameLong: "用户管理",
              cAction: "/ajax/sys/user/",
              cWidgetTypeId: 2,
              cOrderNum: 4,
              cIcon: "",
              WidgetType: "MenuItem"
            },
            {
              cId: "7-4-1",
              cRootId: "7",
              cParentId: "7-4",
              cNameShort: "",
              cNameLong: "新建",
              cAction: "/ajax/sys/user/add.do",
              cWidgetTypeId: 3,
              cOrderNum: 1,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Add",
              CommandName: "Add"
            },
            {
              cId: "7-4-2",
              cRootId: "7",
              cParentId: "7-4",
              cNameShort: "",
              cNameLong: "编辑",
              cAction: "/ajax/sys/user/mod.do",
              cWidgetTypeId: 3,
              cOrderNum: 2,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Mod",
              CommandName: "Modify"
            },
            {
              cId: "7-4-3",
              cRootId: "7",
              cParentId: "7-4",
              cNameShort: "",
              cNameLong: "删除",
              cAction: "/ajax/sys/user/del.do",
              cWidgetTypeId: 3,
              cOrderNum: 3,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Del",
              CommandName: "Delete"
            },
            {
              cId: "7-4-4",
              cRootId: "7",
              cParentId: "7-4",
              cNameShort: "",
              cNameLong: "启用/停用",
              cAction: "/ajax/sys/user/enable.do",
              cWidgetTypeId: 3,
              cOrderNum: 4,
              cIcon: "",
              WidgetType: "Command",
              CommandCode: "Enable",
              CommandName: "Enable"
            }
          ]
        }
      }
    },
    detail: "Ok"
  };
}
