export default function () {
  return {
    "code": 200,
    "data": {
      "cId": "16010100000001",
      "cOrgId": "16010100000001",
      "cName": "系统管理员",
      "cDesc": "系统超级管理员",
      "cRankId": 4,
      "rootFuncs": [{
        "cId": "7",
        "cRootId": "7",
        "cParentId": "7",
        "cNameShort": "系统",
        "cNameLong": "系统管理",
        "cAction": "/ajax/sys/",
        "cWidgetTypeId": 1,
        "cOrderNum": 7,
        "cIcon": "",
        "WidgetType": "Menu"
      }],
      "functions": [{
        "cId": "7",
        "cRootId": "7",
        "cParentId": "7",
        "cNameShort": "系统",
        "cNameLong": "系统管理",
        "cAction": "/ajax/sys/",
        "cWidgetTypeId": 1,
        "cOrderNum": 7,
        "cIcon": "",
        "WidgetType": "Menu"
      }, {
        "cId": "7-1",
        "cRootId": "7",
        "cParentId": "7",
        "cNameShort": "",
        "cNameLong": "组织管理",
        "cAction": "/ajax/sys/",
        "cWidgetTypeId": 2,
        "cOrderNum": 1,
        "cIcon": "",
        "WidgetType": "MenuItem"
      }, {
        "cId": "7-1-1",
        "cRootId": "7",
        "cParentId": "7-1",
        "cNameShort": "",
        "cNameLong": "新建",
        "cAction": "/ajax/sys/org/add.do",
        "cWidgetTypeId": 3,
        "cOrderNum": 1,
        "cIcon": "",
        "WidgetType": "Command",
        "CommandCode": "Add",
        "CommandName": "Add"
      }, {
        "cId": "7-1-2",
        "cRootId": "7",
        "cParentId": "7-1",
        "cNameShort": "",
        "cNameLong": "编辑",
        "cAction": "/ajax/sys/org/mod.do",
        "cWidgetTypeId": 3,
        "cOrderNum": 2,
        "cIcon": "",
        "WidgetType": "Command",
        "CommandCode": "Mod",
        "CommandName": "Modify"
      }, {
        "cId": "7-1-3",
        "cRootId": "7",
        "cParentId": "7-1",
        "cNameShort": "",
        "cNameLong": "删除",
        "cAction": "/ajax/sys/org/del.do",
        "cWidgetTypeId": 3,
        "cOrderNum": 3,
        "cIcon": "",
        "WidgetType": "Command",
        "CommandCode": "Del",
        "CommandName": "Delete"
      }, {
        "cId": "7-2",
        "cRootId": "7",
        "cParentId": "7",
        "cNameShort": "",
        "cNameLong": "角色管理",
        "cAction": "/ajax/sys/role/",
        "cWidgetTypeId": 2,
        "cOrderNum": 2,
        "cIcon": "",
        "WidgetType": "MenuItem"
      }, {
        "cId": "7-2-1",
        "cRootId": "7",
        "cParentId": "7-2",
        "cNameShort": "",
        "cNameLong": "新建",
        "cAction": "/ajax/sys/role/add.do",
        "cWidgetTypeId": 3,
        "cOrderNum": 1,
        "cIcon": "",
        "WidgetType": "Command",
        "CommandCode": "Add",
        "CommandName": "Add"
      }, {
        "cId": "7-2-2",
        "cRootId": "7",
        "cParentId": "7-2",
        "cNameShort": "",
        "cNameLong": "编辑",
        "cAction": "/ajax/sys/role/mod.do",
        "cWidgetTypeId": 3,
        "cOrderNum": 2,
        "cIcon": "",
        "WidgetType": "Command",
        "CommandCode": "Mod",
        "CommandName": "Modify"
      }, {
        "cId": "7-2-3",
        "cRootId": "7",
        "cParentId": "7-2",
        "cNameShort": "",
        "cNameLong": "删除",
        "cAction": "/ajax/sys/role/del.do",
        "cWidgetTypeId": 3,
        "cOrderNum": 3,
        "cIcon": "",
        "WidgetType": "Command",
        "CommandCode": "Del",
        "CommandName": "Delete"
      }, {
        "cId": "7-3",
        "cRootId": "7",
        "cParentId": "7",
        "cNameShort": "",
        "cNameLong": "权限管理",
        "cAction": "/ajax/sys/role/",
        "cWidgetTypeId": 2,
        "cOrderNum": 3,
        "cIcon": "",
        "WidgetType": "MenuItem"
      }, {
        "cId": "7-3-1",
        "cRootId": "7",
        "cParentId": "7-3",
        "cNameShort": "",
        "cNameLong": "授权",
        "cAction": "/ajax/sys/role/auth.do",
        "cWidgetTypeId": 3,
        "cOrderNum": 1,
        "cIcon": "",
        "WidgetType": "Command",
        "CommandCode": "Auth",
        "CommandName": "Authorize"
      }, {
        "cId": "7-4",
        "cRootId": "7",
        "cParentId": "7",
        "cNameShort": "",
        "cNameLong": "用户管理",
        "cAction": "/ajax/sys/user/",
        "cWidgetTypeId": 2,
        "cOrderNum": 4,
        "cIcon": "",
        "WidgetType": "MenuItem"
      }, {
        "cId": "7-4-1",
        "cRootId": "7",
        "cParentId": "7-4",
        "cNameShort": "",
        "cNameLong": "新建",
        "cAction": "/ajax/sys/user/add.do",
        "cWidgetTypeId": 3,
        "cOrderNum": 1,
        "cIcon": "",
        "WidgetType": "Command",
        "CommandCode": "Add",
        "CommandName": "Add"
      }, {
        "cId": "7-4-2",
        "cRootId": "7",
        "cParentId": "7-4",
        "cNameShort": "",
        "cNameLong": "编辑",
        "cAction": "/ajax/sys/user/mod.do",
        "cWidgetTypeId": 3,
        "cOrderNum": 2,
        "cIcon": "",
        "WidgetType": "Command",
        "CommandCode": "Mod",
        "CommandName": "Modify"
      }, {
        "cId": "7-4-3",
        "cRootId": "7",
        "cParentId": "7-4",
        "cNameShort": "",
        "cNameLong": "删除",
        "cAction": "/ajax/sys/user/del.do",
        "cWidgetTypeId": 3,
        "cOrderNum": 3,
        "cIcon": "",
        "WidgetType": "Command",
        "CommandCode": "Del",
        "CommandName": "Delete"
      }, {
        "cId": "7-4-4",
        "cRootId": "7",
        "cParentId": "7-4",
        "cNameShort": "",
        "cNameLong": "启用/停用",
        "cAction": "/ajax/sys/user/enable.do",
        "cWidgetTypeId": 3,
        "cOrderNum": 4,
        "cIcon": "",
        "WidgetType": "Command",
        "CommandCode": "Enable",
        "CommandName": "Enable"
      }]
    },
    "detail": "Ok"
  }
  // return {
  //   "code": 200,
  //   "data": {
  //     "cId": "16122700000033",
  //     "cOrgId": "16122700000032",
  //     "cName": "CEO",
  //     "cDesc": "",
  //     "cRankId": 1,
  //     "rootFuncs": [{
  //       "cId": "1",
  //       "cRootId": "1",
  //       "cParentId": "1",
  //       "cNameShort": "市场",
  //       "cNameLong": "市场管理",
  //       "cAction": "/ajax/mkt/",
  //       "cWidgetTypeId": 1,
  //       "cOrderNum": 1,
  //       "cIcon": "",
  //       "WidgetType": "Menu"
  //     }, {
  //       "cId": "2",
  //       "cRootId": "2",
  //       "cParentId": "2",
  //       "cNameShort": "销售",
  //       "cNameLong": "销售管理",
  //       "cAction": "/ajax/sales",
  //       "cWidgetTypeId": 1,
  //       "cOrderNum": 2,
  //       "cIcon": "",
  //       "WidgetType": "Menu"
  //     }, {
  //       "cId": "3",
  //       "cRootId": "3",
  //       "cParentId": "3",
  //       "cNameShort": "客服",
  //       "cNameLong": "客户服务",
  //       "cAction": "/ajax/service",
  //       "cWidgetTypeId": 1,
  //       "cOrderNum": 3,
  //       "cIcon": "",
  //       "WidgetType": "Menu"
  //     }, {
  //       "cId": "4",
  //       "cRootId": "4",
  //       "cParentId": "4",
  //       "cNameShort": "财务",
  //       "cNameLong": "财务管理",
  //       "cAction": "/ajax/finance",
  //       "cWidgetTypeId": 1,
  //       "cOrderNum": 4,
  //       "cIcon": "",
  //       "WidgetType": "Menu"
  //     }, {
  //       "cId": "5",
  //       "cRootId": "5",
  //       "cParentId": "5",
  //       "cNameShort": "教务",
  //       "cNameLong": "教务管理",
  //       "cAction": "/ajax/academy",
  //       "cWidgetTypeId": 1,
  //       "cOrderNum": 5,
  //       "cIcon": "",
  //       "WidgetType": "Menu"
  //     }, {
  //       "cId": "6",
  //       "cRootId": "6",
  //       "cParentId": "6",
  //       "cNameShort": "教学",
  //       "cNameLong": "教学管理",
  //       "cAction": "/ajax/education",
  //       "cWidgetTypeId": 1,
  //       "cOrderNum": 6,
  //       "cIcon": "",
  //       "WidgetType": "Menu"
  //     }],
  //     "functions": [{
  //       "cId": "1",
  //       "cRootId": "1",
  //       "cParentId": "1",
  //       "cNameShort": "市场",
  //       "cNameLong": "市场管理",
  //       "cAction": "/ajax/mkt/",
  //       "cWidgetTypeId": 1,
  //       "cOrderNum": 1,
  //       "cIcon": "",
  //       "WidgetType": "Menu"
  //     }, {
  //       "cId": "1-1",
  //       "cRootId": "1",
  //       "cParentId": "1",
  //       "cNameShort": "",
  //       "cNameLong": "市场活动",
  //       "cAction": "/ajax/mkt/",
  //       "cWidgetTypeId": 2,
  //       "cOrderNum": 1,
  //       "cIcon": "",
  //       "WidgetType": "MenuItem"
  //     }, {
  //       "cId": "1-1-1",
  //       "cRootId": "1",
  //       "cParentId": "1-1",
  //       "cNameShort": "",
  //       "cNameLong": "新建",
  //       "cAction": "/ajax/mkt/activity/add.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 1,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Add",
  //       "CommandName": "Add"
  //     }, {
  //       "cId": "1-1-2",
  //       "cRootId": "1",
  //       "cParentId": "1-1",
  //       "cNameShort": "",
  //       "cNameLong": "编辑",
  //       "cAction": "/ajax/mkt/activity/mod.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 2,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Mod",
  //       "CommandName": "Modify"
  //     }, {
  //       "cId": "1-1-3",
  //       "cRootId": "1",
  //       "cParentId": "1-1",
  //       "cNameShort": "",
  //       "cNameLong": "删除",
  //       "cAction": "/ajax/mkt/activity/del.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 3,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Del",
  //       "CommandName": "Delete"
  //     }, {
  //       "cId": "1-2",
  //       "cRootId": "1",
  //       "cParentId": "1",
  //       "cNameShort": "",
  //       "cNameLong": "销售线索",
  //       "cAction": "/ajax/mkt/",
  //       "cWidgetTypeId": 2,
  //       "cOrderNum": 1,
  //       "cIcon": "",
  //       "WidgetType": "MenuItem"
  //     }, {
  //       "cId": "1-2-1",
  //       "cRootId": "1",
  //       "cParentId": "1-2",
  //       "cNameShort": "",
  //       "cNameLong": "新建",
  //       "cAction": "/ajax/mkt/leads/add.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 1,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Add",
  //       "CommandName": "Add"
  //     }, {
  //       "cId": "1-2-2",
  //       "cRootId": "1",
  //       "cParentId": "1-2",
  //       "cNameShort": "",
  //       "cNameLong": "编辑",
  //       "cAction": "/ajax/mkt/leads/mod.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 2,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Mod",
  //       "CommandName": "Modify"
  //     }, {
  //       "cId": "1-2-3",
  //       "cRootId": "1",
  //       "cParentId": "1-2",
  //       "cNameShort": "",
  //       "cNameLong": "删除",
  //       "cAction": "/ajax/mkt/leads/del.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 3,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Del",
  //       "CommandName": "Delete"
  //     }, {
  //       "cId": "1-2-4",
  //       "cRootId": "1",
  //       "cParentId": "1-2",
  //       "cNameShort": "",
  //       "cNameLong": "导入",
  //       "cAction": "/ajax/mkt/leads/import.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 4,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Import",
  //       "CommandName": "Import"
  //     }, {
  //       "cId": "1-2-5",
  //       "cRootId": "1",
  //       "cParentId": "1-2",
  //       "cNameShort": "",
  //       "cNameLong": "分配",
  //       "cAction": "/ajax/mkt/leads/assign.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 5,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Assign",
  //       "CommandName": "Assign"
  //     }, {
  //       "cId": "1-2-6",
  //       "cRootId": "1",
  //       "cParentId": "1-2",
  //       "cNameShort": "",
  //       "cNameLong": "转化",
  //       "cAction": "/ajax/mkt/leads/convert.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 6,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Convert",
  //       "CommandName": "Convert"
  //     }, {
  //       "cId": "2",
  //       "cRootId": "2",
  //       "cParentId": "2",
  //       "cNameShort": "销售",
  //       "cNameLong": "销售管理",
  //       "cAction": "/ajax/sales",
  //       "cWidgetTypeId": 1,
  //       "cOrderNum": 2,
  //       "cIcon": "",
  //       "WidgetType": "Menu"
  //     }, {
  //       "cId": "2-1",
  //       "cRootId": "2",
  //       "cParentId": "2",
  //       "cNameShort": "",
  //       "cNameLong": "销售机会",
  //       "cAction": "/ajax/sales/",
  //       "cWidgetTypeId": 2,
  //       "cOrderNum": 1,
  //       "cIcon": "",
  //       "WidgetType": "MenuItem"
  //     }, {
  //       "cId": "2-1-1",
  //       "cRootId": "2",
  //       "cParentId": "2-1",
  //       "cNameShort": "",
  //       "cNameLong": "新建",
  //       "cAction": "/ajax/sales/oppor/add.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 1,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Add",
  //       "CommandName": "Add"
  //     }, {
  //       "cId": "2-1-2",
  //       "cRootId": "2",
  //       "cParentId": "2-1",
  //       "cNameShort": "",
  //       "cNameLong": "编辑",
  //       "cAction": "/ajax/sales/oppor/mod.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 2,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Mod",
  //       "CommandName": "Modify"
  //     }, {
  //       "cId": "2-1-3",
  //       "cRootId": "2",
  //       "cParentId": "2-1",
  //       "cNameShort": "",
  //       "cNameLong": "删除",
  //       "cAction": "/ajax/sales/oppor/del.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 3,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Del",
  //       "CommandName": "Delete"
  //     }, {
  //       "cId": "2-1-5",
  //       "cRootId": "2",
  //       "cParentId": "2-1",
  //       "cNameShort": "",
  //       "cNameLong": "分配",
  //       "cAction": "/ajax/sales/oppor/assign.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 5,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Assign",
  //       "CommandName": "Assign"
  //     }, {
  //       "cId": "2-1-6",
  //       "cRootId": "2",
  //       "cParentId": "2-1",
  //       "cNameShort": "",
  //       "cNameLong": "创建合同",
  //       "cAction": "/ajax/sales/oppor/sign.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 6,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Sign",
  //       "CommandName": "Sign"
  //     }, {
  //       "cId": "2-2",
  //       "cRootId": "2",
  //       "cParentId": "2",
  //       "cNameShort": "",
  //       "cNameLong": "我的合同",
  //       "cAction": "/ajax/sales/contract/",
  //       "cWidgetTypeId": 2,
  //       "cOrderNum": 1,
  //       "cIcon": "",
  //       "WidgetType": "MenuItem"
  //     }, {
  //       "cId": "2-2-1",
  //       "cRootId": "2",
  //       "cParentId": "2-2",
  //       "cNameShort": "",
  //       "cNameLong": "新建合同",
  //       "cAction": "/ajax/sales/contract/add.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 1,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Add",
  //       "CommandName": "Add"
  //     }, {
  //       "cId": "2-2-2",
  //       "cRootId": "2",
  //       "cParentId": "2-2",
  //       "cNameShort": "",
  //       "cNameLong": "编辑合同",
  //       "cAction": "/ajax/sales/contract/mod.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 2,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Mod",
  //       "CommandName": "Modify"
  //     }, {
  //       "cId": "2-2-3",
  //       "cRootId": "2",
  //       "cParentId": "2-2",
  //       "cNameShort": "",
  //       "cNameLong": "删除合同",
  //       "cAction": "/ajax/sales/contract/del.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 3,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Del",
  //       "CommandName": "Delete"
  //     }, {
  //       "cId": "2-3",
  //       "cRootId": "2",
  //       "cParentId": "2-3",
  //       "cNameShort": "",
  //       "cNameLong": "我的学员",
  //       "cAction": "/ajax/sales/customer/",
  //       "cWidgetTypeId": 2,
  //       "cOrderNum": 1,
  //       "cIcon": "",
  //       "WidgetType": "MenuItem"
  //     }, {
  //       "cId": "2-3-1",
  //       "cRootId": "2",
  //       "cParentId": "2-3",
  //       "cNameShort": "",
  //       "cNameLong": "新建学员信息",
  //       "cAction": "/ajax/sales/customer/student/add.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 1,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Add",
  //       "CommandName": "Add"
  //     }, {
  //       "cId": "2-3-2",
  //       "cRootId": "2",
  //       "cParentId": "2-3",
  //       "cNameShort": "",
  //       "cNameLong": "编辑学员信息",
  //       "cAction": "/ajax/sales/customer/student/mod.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 2,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Mod",
  //       "CommandName": "Modify"
  //     }, {
  //       "cId": "2-3-3",
  //       "cRootId": "2",
  //       "cParentId": "2-3",
  //       "cNameShort": "",
  //       "cNameLong": "删除学员信息",
  //       "cAction": "/ajax/sales/customer/student/del.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 3,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Del",
  //       "CommandName": "Delete"
  //     }, {
  //       "cId": "2-3-4",
  //       "cRootId": "2",
  //       "cParentId": "2-3",
  //       "cNameShort": "",
  //       "cNameLong": "新建家长信息",
  //       "cAction": "/ajax/sales/customer/parent/add.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 4,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Add",
  //       "CommandName": "Add"
  //     }, {
  //       "cId": "2-3-5",
  //       "cRootId": "2",
  //       "cParentId": "2-3",
  //       "cNameShort": "",
  //       "cNameLong": "编辑家长信息",
  //       "cAction": "/ajax/sales/customer/parent/mod.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 5,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Mod",
  //       "CommandName": "Modify"
  //     }, {
  //       "cId": "2-3-6",
  //       "cRootId": "2",
  //       "cParentId": "2-3",
  //       "cNameShort": "",
  //       "cNameLong": "删除家长信息",
  //       "cAction": "/ajax/sales/customer/parent/del.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 6,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Del",
  //       "CommandName": "Delete"
  //     }, {
  //       "cId": "3",
  //       "cRootId": "3",
  //       "cParentId": "3",
  //       "cNameShort": "客服",
  //       "cNameLong": "客户服务",
  //       "cAction": "/ajax/service",
  //       "cWidgetTypeId": 1,
  //       "cOrderNum": 3,
  //       "cIcon": "",
  //       "WidgetType": "Menu"
  //     }, {
  //       "cId": "3-1",
  //       "cRootId": "3",
  //       "cParentId": "3",
  //       "cNameShort": "",
  //       "cNameLong": "合同管理",
  //       "cAction": "/ajax/service/contract/",
  //       "cWidgetTypeId": 2,
  //       "cOrderNum": 1,
  //       "cIcon": "",
  //       "WidgetType": "MenuItem"
  //     }, {
  //       "cId": "3-1-1",
  //       "cRootId": "3",
  //       "cParentId": "3-1",
  //       "cNameShort": "",
  //       "cNameLong": "新建合同",
  //       "cAction": "/ajax/service/contract/add.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 1,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Add",
  //       "CommandName": "Add"
  //     }, {
  //       "cId": "3-1-2",
  //       "cRootId": "3",
  //       "cParentId": "3-1",
  //       "cNameShort": "",
  //       "cNameLong": "编辑合同",
  //       "cAction": "/ajax/service/contract/mod.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 2,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Mod",
  //       "CommandName": "Modify"
  //     }, {
  //       "cId": "3-1-3",
  //       "cRootId": "3",
  //       "cParentId": "3-1",
  //       "cNameShort": "",
  //       "cNameLong": "删除合同",
  //       "cAction": "/ajax/service/contract/del.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 3,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Del",
  //       "CommandName": "Delete"
  //     }, {
  //       "cId": "3-2",
  //       "cRootId": "3",
  //       "cParentId": "3",
  //       "cNameShort": "",
  //       "cNameLong": "学员管理",
  //       "cAction": "/ajax/service/customer/",
  //       "cWidgetTypeId": 2,
  //       "cOrderNum": 1,
  //       "cIcon": "",
  //       "WidgetType": "MenuItem"
  //     }, {
  //       "cId": "3-2-1",
  //       "cRootId": "3",
  //       "cParentId": "3-2",
  //       "cNameShort": "",
  //       "cNameLong": "新建学员信息",
  //       "cAction": "/ajax/service/customer/student/add.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 1,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Add",
  //       "CommandName": "Add"
  //     }, {
  //       "cId": "3-2-2",
  //       "cRootId": "3",
  //       "cParentId": "3-2",
  //       "cNameShort": "",
  //       "cNameLong": "编辑学员信息",
  //       "cAction": "/ajax/service/customer/student/mod.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 2,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Mod",
  //       "CommandName": "Modify"
  //     }, {
  //       "cId": "3-2-3",
  //       "cRootId": "3",
  //       "cParentId": "3-2",
  //       "cNameShort": "",
  //       "cNameLong": "删除学员信息",
  //       "cAction": "/ajax/service/customer/student/del.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 3,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Del",
  //       "CommandName": "Delete"
  //     }, {
  //       "cId": "3-2-4",
  //       "cRootId": "3",
  //       "cParentId": "3-2",
  //       "cNameShort": "",
  //       "cNameLong": "新建家长信息",
  //       "cAction": "/ajax/service/customer/parent/add.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 4,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Add",
  //       "CommandName": "Add"
  //     }, {
  //       "cId": "3-2-5",
  //       "cRootId": "3",
  //       "cParentId": "3-2",
  //       "cNameShort": "",
  //       "cNameLong": "编辑家长信息",
  //       "cAction": "/ajax/service/customer/parent/mod.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 5,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Mod",
  //       "CommandName": "Modify"
  //     }, {
  //       "cId": "3-2-6",
  //       "cRootId": "3",
  //       "cParentId": "3-2",
  //       "cNameShort": "",
  //       "cNameLong": "删除家长信息",
  //       "cAction": "/ajax/service/customer/parent/del.do",
  //       "cWidgetTypeId": 3,
  //       "cOrderNum": 6,
  //       "cIcon": "",
  //       "WidgetType": "Command",
  //       "CommandCode": "Del",
  //       "CommandName": "Delete"
  //     }, {
  //       "cId": "4",
  //       "cRootId": "4",
  //       "cParentId": "4",
  //       "cNameShort": "财务",
  //       "cNameLong": "财务管理",
  //       "cAction": "/ajax/finance",
  //       "cWidgetTypeId": 1,
  //       "cOrderNum": 4,
  //       "cIcon": "",
  //       "WidgetType": "Menu"
  //     }, {
  //       "cId": "5",
  //       "cRootId": "5",
  //       "cParentId": "5",
  //       "cNameShort": "教务",
  //       "cNameLong": "教务管理",
  //       "cAction": "/ajax/academy",
  //       "cWidgetTypeId": 1,
  //       "cOrderNum": 5,
  //       "cIcon": "",
  //       "WidgetType": "Menu"
  //     }, {
  //       "cId": "6",
  //       "cRootId": "6",
  //       "cParentId": "6",
  //       "cNameShort": "教学",
  //       "cNameLong": "教学管理",
  //       "cAction": "/ajax/education",
  //       "cWidgetTypeId": 1,
  //       "cOrderNum": 6,
  //       "cIcon": "",
  //       "WidgetType": "Menu"
  //     }]
  //   },
  //   "detail": "Ok"
  // }
}