export default function () {
  return {
    "code": 200,
    "data": [{
      "cId": "16122700000032",
      "cName": "系统管理员",
      "cDesc": "",
      "cRankName": "系统管理员",
      "rootFuncs": [{
        "cId": "7",
        "cRootId": "7",
        "cParentId": "7",
        "cNameShort": "系统",
        "cNameLong": "系统管理",
        "cAction": "/ajax/sys/",
        "cWidgetTypeId": 1,
        "cOrderNum": 7,
        "cIcon": "",
        "WidgetType": "Menu"
      }]
    }, {
      "cId": "16122700000033",
      "cName": "CEO",
      "cDesc": "",
      "cRankName": "经理",
      "rootFuncs": [{
        "cId": "1",
        "cRootId": "1",
        "cParentId": "1",
        "cNameShort": "市场",
        "cNameLong": "市场管理",
        "cAction": "/ajax/mkt/",
        "cWidgetTypeId": 1,
        "cOrderNum": 1,
        "cIcon": "",
        "WidgetType": "Menu"
      }, {
        "cId": "2",
        "cRootId": "2",
        "cParentId": "2",
        "cNameShort": "销售",
        "cNameLong": "销售管理",
        "cAction": "/ajax/sales",
        "cWidgetTypeId": 1,
        "cOrderNum": 2,
        "cIcon": "",
        "WidgetType": "Menu"
      }, {
        "cId": "3",
        "cRootId": "3",
        "cParentId": "3",
        "cNameShort": "客服",
        "cNameLong": "客户服务",
        "cAction": "/ajax/service",
        "cWidgetTypeId": 1,
        "cOrderNum": 3,
        "cIcon": "",
        "WidgetType": "Menu"
      }, {
        "cId": "4",
        "cRootId": "4",
        "cParentId": "4",
        "cNameShort": "财务",
        "cNameLong": "财务管理",
        "cAction": "/ajax/finance",
        "cWidgetTypeId": 1,
        "cOrderNum": 4,
        "cIcon": "",
        "WidgetType": "Menu"
      }, {
        "cId": "5",
        "cRootId": "5",
        "cParentId": "5",
        "cNameShort": "教务",
        "cNameLong": "教务管理",
        "cAction": "/ajax/academy",
        "cWidgetTypeId": 1,
        "cOrderNum": 5,
        "cIcon": "",
        "WidgetType": "Menu"
      }, {
        "cId": "6",
        "cRootId": "6",
        "cParentId": "6",
        "cNameShort": "教学",
        "cNameLong": "教学管理",
        "cAction": "/ajax/education",
        "cWidgetTypeId": 1,
        "cOrderNum": 6,
        "cIcon": "",
        "WidgetType": "Menu"
      }]
    }, {
      "cId": "16122700000037",
      "cName": "销售总监",
      "cDesc": "",
      "cRankName": "主管",
      "rootFuncs": [{
        "cId": "2",
        "cRootId": "2",
        "cParentId": "2",
        "cNameShort": "销售",
        "cNameLong": "销售管理",
        "cAction": "/ajax/sales",
        "cWidgetTypeId": 1,
        "cOrderNum": 2,
        "cIcon": "",
        "WidgetType": "Menu"
      }]
    }],
    "detail": "Ok"
  }
}